version: '3'
services:
  app:
    image: emmettwoo/emm-moneybox:build
    build:
      context: ..
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGO_DB_URI=${MONGO_DB_URI}
      - MYSQL_DB_URI=${MYSQL_DB_URI}
